source 'https://rubygems.org'

# Specify your gem's dependencies in aggregator.gemspec
gemspec

gem 'sidekiq', '4.0.1'

# gem 'airbrake-ruby', '~> 1.1'

# facebook
gem 'koala'
gem 'retriable', '~> 1.4'
# spotify
gem 'rspotify'

# youtube
gem 'yourub', '2.0.2'
gem 'google-api-client', '0.8.6'

gem 'yt'
gem 'soundcloud'
gem 'nokogiri', '1.6.7.rc3'

gem 'simple-conf'
gem 'faraday'
gem 'naught'
gem 'le'
# gem 'facets', '3.1.0', require: false

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-remote'
  gem 'pry-coolline'

  gem 'rspec-core'
  gem 'rspec-mocks'
  gem 'rspec-collection_matchers'
end
